# Generated by Django 5.0 on 2023-12-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_rename_backet_basket"),
    ]

    operations = [
        migrations.RenameField(
            model_name="basket",
            old_name="created_timestamp",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="basket",
            old_name="product",
            new_name="products",
        ),
        migrations.AlterField(
            model_name="basket",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
